-- Tabla de Dimensión de Tiempo
CREATE TABLE IF NOT EXISTS "DimTiempo" (
    "CRASH_DATE" DATE PRIMARY KEY,
    "CRASH_HOUR" INT,
    "CRASH_DAY_OF_WEEK" INT,
    "CRASH_MONTH" INT
);

-- Tabla de Dimensión de Ubicación
CREATE TABLE IF NOT EXISTS "DimUbicacion" (
    "LATITUDE" DECIMAL(9,6),
    "LONGITUDE" DECIMAL(9,6),
    "LOCATION" VARCHAR(255) PRIMARY KEY
);

-- Tabla de Dimensión de Tipo de Accidente
CREATE TABLE IF NOT EXISTS "DimTipoAccidente" (
    "CRASH_TYPE" VARCHAR(255) PRIMARY KEY
);

-- Tabla de Dimensión de Condiciones Climáticas
CREATE TABLE IF NOT EXISTS "DimClima" (
    "WEATHER_CONDITION" VARCHAR(255) PRIMARY KEY
);

-- Tabla de Hechos de Lesiones
CREATE TABLE IF NOT EXISTS "HechosLesiones" (
    "CRASH_DATE" DATE,
    "LATITUDE" DECIMAL(9,6),
    "LONGITUDE" DECIMAL(9,6),
    "LOCATION" VARCHAR(255),
    "CRASH_TYPE" VARCHAR(255),
    "WEATHER_CONDITION" VARCHAR(255),
    "POSTED_SPEED_LIMIT" INT,
    "INJURIES_TOTAL" INT,
    "INJURIES_FATAL" INT,
    "INJURIES_INCAPACITATING" INT,
    "INJURIES_NON_INCAPACITATING" INT,
    "INJURIES_REPORTED_NOT_EVIDENT" INT,
    "INJURIES_NO_INDICATION" INT,
    "INJURIES_UNKNOWN" INT,
    PRIMARY KEY ("CRASH_DATE", "LOCATION", "CRASH_TYPE"),
    FOREIGN KEY ("CRASH_DATE") REFERENCES "DimTiempo"("CRASH_DATE"),
    FOREIGN KEY ("LOCATION") REFERENCES "DimUbicacion"("LOCATION"),
    FOREIGN KEY ("CRASH_TYPE") REFERENCES "DimTipoAccidente"("CRASH_TYPE"),
    FOREIGN KEY ("WEATHER_CONDITION") REFERENCES "DimClima"("WEATHER_CONDITION")
);